services:
  app:
    image: tannguyen1404/grade-portal-be-kotlin:latest
    build:
      context: .              # Thư mục chứa Dockerfile
      dockerfile: Dockerfile  # Sử dụng Dockerfile tại thư mục gốc
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}" # Map cổng từ container ra máy chủ
    env_file:
      - .env                  # Sử dụng file .env chứa các biến môi trường
    networks:
      - app-network
networks:
  app-network:
    driver: bridge