spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
  mail:
    host: smtp.gmail.com
    port: 587
    username: gradeportaldath@gmail.com
    password: jdbzixmrsxkndork
    properties:
      auth: true
      starttls:
        enable: true
      debug: true

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}

jwt:
  signerKey: ${JWT_SIGNER_KEY}